name = "ML_as_MO"
uuid = "871ff0e3-44a5-4569-9f8c-43c8af2866ab"
authors = ["Joonatan Linkola", "Eetu Reijonen", "Nikita Belyak", "Fabricio Oliveira"]
version = "1.0.0-DEV"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Flux = "0.13"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
